(* ::Package:: *)

(* ::Text:: *)
(*Copyright (C) 2025 Yiman Gao*)
(*Copyright (C) 2026 Jakob Obrovsky*)
(**)
(*This file is part of CRforDR.*)
(**)
(*CRforDR is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License (LGPL) as published by the Free Software Foundation; either version 3 of the License, or  (at your option) any later version.  See https://www.gnu.org/licenses/*)


(* ::Input::Initialization:: *)
BeginPackage["Rational`"];
ClearAll@@Names["Rational`*"];


(* ::Input::Initialization:: *)
AMonicFactor::usage="";
Euclidean::usage="";
ExtendedEuclidean::usage="";
ParFracDecomp::usage="";
ProperAndPolynomialParts::usage="";
NormallyProperAndLaurentPolynomialParts::usage="";
PadicExpand::usage="";
MyCoefficient0::usage="";
MyCoefficientNew::usage="";
BasisElement0::usage="";
BasisElement::usage="";
DispersionSet ::usage="";
PrimitiveRNF ::usage="";
RNF ::usage="";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
(* Input: a polynomial with degree(p,var)>0. *)
(* Output: The monic irreducible factor q with respect to var and m is the multiplicity of q. *)
AMonicFactor[p_,var_Symbol]:=Module[{ps, L,q},
ps=FactorTermsList[p,var];
L =FactorList[ps[[-1]]];
q=Cancel[L[[2]][[1]]/Coefficient[L[[2]][[1]],var,Exponent[L[[2]][[1]],var]]];
{q,L[[2]][[2]]}];



(* ::Input::Initialization:: *)
(* Input: Two rational functions a and b which are polynomials in the variable var. *)
(* Output: The monic gcd of the numerators of a and b with respect to var. *)
Euclidean[a_,b_,var_Symbol]:=Module[{g},
(* Observe that we are taking the GCD of their numerators (which are polynomials). *)
g=PolynomialGCD@@({a,b}//Together//Numerator);
(* The main difference in this function compared to PolynomialGCD is that we make the gcd monic with respect to the desired variable. *)
g=Cancel[g/Coefficient[g,var,Exponent[g,var]]]
];


(* ::Input::Initialization:: *)
(* Input: Three polynomials a, b and c in var. *)
(* Output: Two polynomials r and s such that r a + s b = c and degree of r in var is lower than that of b. *)
ExtendedEuclidean[a_,b_,c_,var_Symbol]:=Module[{a1=Together[a],b1=Together[b],c1=Together[c],g,r,s,h,r1,rem,q},
{g,{r,s}}=PolynomialExtendedGCD[a1,b1,var];
{h,rem}=PolynomialQuotientRemainder[c1,g,var];
If[rem=!=0,Throw["Error in ExtendedEuclidean: c is not in the ideal generated by a and b."],
{r,s}=Cancel[h {r,s}];
(* In this case we take care to keep track of the main variable to give the correct output in terms of the main variable. *)
If[!(r===0)&&Exponent[b1,var]<= Exponent[r,var],
(* An ad hoc trick: we only compute the quotient and remainder of the numerators in order to save time (because we know that it is a polynomial in terms of var). *)
{q,r1}=PolynomialQuotientRemainder[Numerator[r],Numerator[b1],var];
(* We remember to return the denominator here! *)
s=Together[q a1 Denominator[b1]/Denominator[r]+s];
{r1/Denominator[r],s},
{r,s}]]];


(* ::Input::Initialization:: *)
(*Input: a, a polynomial in K[y];
        [d_1,...,d_m], a list of polynomials in K[y] with
         deg(a)<deg(d_1*d_2...*d_m)
       deg(d_i)>0 and gcd(d_i,d_j)=1 for i<>j;
  Output:{a_1,a_2,...,a_m}, where a_i is a polynomial with deg(a_i)<deg(d_i) and gcd(a_i,d_i)=1
        such that a/(d_1*...*d_m)=a_1/d_1+...a_m/d_m.
*)

ParFracDecomp[a_, T_List,y_]:= Module[{n,a1,s,t,W},
 n=Length[T];
If[n===1, Return[{a}]];
t= Product[T[[i]],{i,2,n}];
{a1,s}=ExtendedEuclidean[t,T[[1]],a,y];
W = ParFracDecomp[s,Drop[T,{1}] ,y];
PrependTo[W, a1]
];


(* ::Input::Initialization:: *)
(* Input: A rational function  in var. *)
(* Output: the proper fraction part fp of f and the polynomial part of f. *)


(* ::Input::Initialization:: *)
ProperAndPolynomialParts[f_,var_Symbol]:=Module[{ff,num,den,r,pp,fp},
ff=Together[f];
num=Numerator[ff];
den=Denominator[ff];
{pp,r}=PolynomialQuotientRemainder[num,den,var];
fp = Cancel[r/den];
{fp,pp}
];



(* ::Input::Initialization:: *)
(* Input: A rational function in var. *)
(* Output: the proper fraction part fp of f and the Laurent polynomial part of f. *)


(* ::Input::Initialization:: *)
NormallyProperAndLaurentPolynomialParts[f_,var_Symbol]:=Module[{ff,num,den,r,pp,fp,b,i,u,v,f1,f2},
ff=Together[f];
num=Numerator[ff];
den=Denominator[ff];
{pp,r}=PolynomialQuotientRemainder[num,den,var];
fp = Cancel[r/den];
b = den;
(*Compute ord_t(den(f))*)
i =0;
While[PolynomialQuotientRemainder[b,var,var][[2]]===0, b=PolynomialQuotientRemainder[b,var,var][[1]];i++];
{u,v}=Catch[ExtendedEuclidean[var^i,b,r,var]];
f1=Cancel[u/b];
f2=Expand[v/var^i]+pp;
{f1,f2}
];


(* ::Input::Initialization:: *)
(* Input:f, p two polynomials in var with deg(p,x)>0
 Output: {f0,f1,...,fk}, where fi in C[var] and deg(fi,x)<deg(p,x) such that f=f0+f1*p+f2*p^2+...+fkp^k mod p^{k+1}
*)


(* ::Input::Initialization:: *)
PadicExpand[f_,p_,k_,var_Symbol]:= Module[ {r,A,L},
If[k===0, Return[{PolynomialRemainder[f,p,var]}]];
A=PolynomialQuotientRemainder[f,p,var];
L=PadicExpand[A[[1]],p,k-1,var];
Prepend[L,A[[2]]]
];


(* ::Input::Initialization:: *)
$activateEcho=False;


(* ::Input::Initialization:: *)
Clear[myEcho];
myEcho[args___]:=If[$activateEcho,Echo[args]];


(* ::Input::Initialization:: *)
(* Input:f, an element in var
          b={nb,db,mb},representing an element nb/db^mb in the canonical C-basis 
Output: the coefficient of b in f  *)
MyCoefficient0[f_,b_,var_Symbol]:=Module[{fs=Together[f],nb,db,mb,r, p,numr,denr,k,v,A,s, a,c},
{nb, db, mb}=b;
(* trivial case *)
If[fs===0,Return[0]];
{r,p}=ProperAndPolynomialParts[fs,var];
myEcho[{r,p},"{r,p}:"];
(* polynomial case*)
If[db===1,Return[Coefficient[p,var,Exponent[nb,var]]]];
(* fraction case*)
{numr,denr}=NumeratorDenominator[Together[r]];
{numr,denr}={Cancel[numr/Coefficient[denr,var,Exponent[denr,var]]],Cancel[denr/Coefficient[denr,var,Exponent[denr,var]]]};
(*Compute the multiplicity of db in den*)
{k,v}={0,denr};
myEcho[{numr,denr},"{numr,denr}:"];
While[True,A=PolynomialQuotientRemainder[v,db,var];
 If[A[[2]]===0, {k,v}={k+1, A[[1]]},Break[]]
];
myEcho[{k,v},"{k,v}:"];
(*detect divisibility *)
myEcho[k===0 || k<mb,"Testing condition:"];
If [k===0 || k<mb, Return[0]];
(* a partial fraction decomp*)
s=ExtendedEuclidean[v,db^k,1,var][[1]];
a= PadicExpand[numr*s,db,k-mb,var][[k-mb+1]];
c = Coefficient[a,var,Exponent[nb,var]];
myEcho[{s,a,c},"{s,a,c}:"];
c
];


(* ::Input::Initialization:: *)
(*Input:T,a nonempty list of indeterminates,
         f, an element of C(T),
         b, an element in the canonical C-basis of C(T) 
Output: the coefficient of b in f
*)


(* ::Input::Initialization:: *)
$activateEcho=False;
Clear[myEcho];
myEcho[args___]:=If[$activateEcho,Echo[args]];

MyCoefficientNew[T_List,f_, b_]:=Module[{ff=Together[f],n,t,numb,denb,ndeg,ddeg,B,p,m,d,c,bs},
If[ff===0,Return[0]];
n=Length[T];
t=T[[n]];
{numb,denb}=NumeratorDenominator[b];

{ndeg,ddeg}=Exponent[{numb,denb},t];
(*analyze the basis element*)
If[ddeg===0,B={t^ndeg,1,1},{p,m}=AMonicFactor[denb,t]; B={t^ndeg,p,m}];
myEcho[{B},"{B}:"];
(*prepare for recursion*)
c=MyCoefficient0[ff,B,T[[n]]];
myEcho[{c},"{c}:"];
(*recursion*)
If[n===1, Return[c]];
bs=Cancel[b/(B[[1]]/B[[2]]^B[[3]])];
d= MyCoefficientNew[Drop[T,-1],c,bs]
];



(* ::Input::Initialization:: *)
(* Input: f,an element in F(var),
   Output: {b,c}, where b is a pivot of f and c is the corresponding coefficient
*)


(* ::Input::Initialization:: *)
BasisElement0[f_,var_Symbol]:=Module[{ff=Together[f],r,p,d,num,den,m,q,u},
{r,p}=ProperAndPolynomialParts[ff,var];
If[p=!=0,d=Exponent[p,var];Return[{var^d,Coefficient[p,var,d]}]];
{num,den}=NumeratorDenominator[r];
{p,m}=AMonicFactor[den,var];
q = PolynomialQuotient[den,p^m,var];
u=ExtendedEuclidean[q,p^m,1,var][[1]];
r=PolynomialRemainder[num*u,p,var];
d=Exponent[r,var];
{var^d/p^m,Coefficient[r,var,d]}
];


(* ::Input::Initialization:: *)
(*Input: T, a nonempty list of indeterminates,
         f, a nonzero rational function in C(T),
   Output: {b,c}, where b is a pivot of f and c the corresponding coefficient
*)


(* ::Input::Initialization:: *)
BasisElement[T_List,f_]:=Module[{n,ff=Together[f],bp,cp,bs,cs},
n=Length[T];
       If[n===1, Return[BasisElement0[ff,T[[1]]]]];
       
        {bp, cp}=BasisElement0[ff,T[[n]]];
      
         {bs,cs}=BasisElement[Drop[T,-1],cp];
         
          {bs*bp,cs}
];


(* ::Input::Initialization:: *)
(*Input: a,b, two polynomials that has only normal factors in a \PiSigma tower,
  Output: the dispersion set of a,b     
*)


(* ::Input::Initialization:: *)
$activateEcho=False;
Clear[myEcho];
myEcho[args___]:=If[$activateEcho,Echo[args]];
DispersionSet[a_,b_,tower_List]:=Module[{t,A,B,DS,i,j,s,m},
t=tower[[-1]][[1]];
(*trivial case*)
 If [Exponent[a,t]===0||Exponent[b,t]===0, Return[{}]];
  (*obtain all irreducible factors of a and b,respectively*)
A=FactorList[FactorTermsList[a,t][[-1]]];
A=Drop[#[[1]]&/@A,1];
A=Numerator[A];
B=FactorList[FactorTermsList[b,t][[-1]]];
B=Drop[#[[1]]&/@B,1];
B=Numerator[B];
myEcho[{A,B},"{A,B}:"];
(*find the dispersion set*)
DS={};
For[i=1,i<=Length[A],i++,
For[j=1,j<=Length[B],j++,
s=-Sigma`DifferenceFields`BasicTools`DFInterface`GetSpecification[A[[i]],B[[j]],tower];
 If  [s=!=Null,DS=Union[DS,{s}]];
];
];
DS
];


(* ::Input::Initialization:: *)
(*Input: nf,df, two elements in a \PiSigma tower,
  Output: [u,v,s,r],where
            u,v,s,r, 4 primitive polynomials in the tower and s,              r are free of special factor such that
           (1) nf/df=K*\[Sigma](S)/S with K=u/v and S=s/r;
             (2) K is Sy_reduced
           (3) gcd(s,r)=gcd(u,s*\[Sigma](r))=gcd(v,\[Sigma](s)*r)=1
*)


(* ::Input::Initialization:: *)
$activateEcho=False;
Clear[myEcho];
myEcho[args___]:=If[$activateEcho,Echo[args]];
PrimitiveRNF[nf_,df_,tower_List]:=Module[{w1,w2,u,v,s,r,t, DS,pDS,nDS,i,k,p,pk},
(*trivial case*)
{w1,w2}={1,1};
{u, v,s, r}={nf,df,1,1};
t =tower[[-1]][[1]];
If [Exponent[u,t]===0 || Exponent[v,t]===0,Return[{u,v,s,r}]];
(*handle with special factors in the \Pi case*)
If[tower[[-1]][[3]]===0, 
   If[PolynomialRemainder[u,t,t]===0,
u=u/t;
w1=w1*t
];
If[PolynomialRemainder[v,t,t]===0,
v=v/t;
w2=w2*t
];
];
 (*Compute the dispersion set of u and v*)
myEcho[{u,w1,v,w2},"{u,w1,v,w2}:"];
DS=DispersionSet[u,v,tower];
myEcho[{DS},"{DS}:"];
pDS =Select[DS,Positive];
nDS=Select[DS, Negative];
myEcho[{pDS,nDS},"{pDS,nDS}:"];
(*deal with Positive integers*)
For[i=1,i<=Length[pDS],i++,
    k=pDS[[i]];
         p=Euclidean[u,Sigma`DifferenceFields`BasicTools`DFInterface`TSigma[v,k,tower],t];
       pk=Sigma`DifferenceFields`BasicTools`DFInterface`TSigma[p,-k,tower];
    {u,v}={Cancel[u/p],Cancel[v/pk]};       s=s*Product[Sigma`DifferenceFields`BasicTools`DFInterface`TSigma[p,j,tower],{j,1,k-1}]*pk;
myEcho[{p,pk,s},"{p,pk,s}:"];
];
(*deal with negative integers*)
For[i=1,i<=Length[nDS],i++,
    k=nDS[[i]];
         p=Euclidean[u,Sigma`DifferenceFields`BasicTools`DFInterface`TSigma[v,k,tower],t];
       pk=Sigma`DifferenceFields`BasicTools`DFInterface`TSigma[p,-k,tower];
    {u,v}={Cancel[u/p],Cancel[v/pk]};       r=r*Product[Sigma`DifferenceFields`BasicTools`DFInterface`TSigma[p,j,tower],{j,0,-k-1}];
];
{u*w1,v*w2,s,r}
];


(* ::Input::Initialization:: *)
(*Input: tower, a \PiSigma tower,
         f, a nonzero rational function  in a \PiSigma tower,
  Output: [u,v,s,r],where
            u,v,s,r, 4  polynomials w.r.t. the last generator in the tower and s,                    r are free of special factor such that
           (1) nf/df=K*\[Sigma](S)/S with K=u/v and S=s/r;
             (2) K is Sy_reduced
           (3) gcd(s,r)=gcd(u,s*\[Sigma](r))=gcd(v,\[Sigma](s)*r)=1
         (4) v,s,t are primitive w.r.t. the last generator.
*)


(* ::Input::Initialization:: *)
$activateEcho=False;
Clear[myEcho];
myEcho[args___]:=If[$activateEcho,Echo[args]];
RNF[f_,tower_List]:=Module[{ff=Together[f],t,nf,df,A,c,u,v,s,r},
(*trivial case*)
t=tower[[-1]][[1]];
If[FreeQ[ff,t],Return[{f,1,1,1}]];
(*Compute an RNF of the primitive part*)
A=FactorTermsList[#,t]&/@NumeratorDenominator[ff];
myEcho[{A},"{A}:"];
c=ff*A[[2]][[-1]]/A[[1]][[-1]];
myEcho[{c},"{c}:"];
{u,v,s,r}=PrimitiveRNF[A[[1]][[-1]],A[[2]][[-1]],tower];
myEcho[{u,v,s,r},"{u,v,s,r}:"];
u=Together[Cancel[c*u/v]];
{Numerator[u],Denominator[u],s,r}
];


(* ::Input::Initialization:: *)
End[];


(* ::Input::Initialization:: *)
EndPackage[];

